### ISSUE TITLE
1.21 Crash when opening Inventory

### ISSUE THREAD

**Issue by Ecthelion75** [Rajhab/More-Vanilla-Shields-Forge#3]
Tested on neoForge beta 21.0.140 without any other mod present. Mod crashes specifically when opening inventory.

[crash-2024-07-28_13.08.44-client.txt](https://github.com/user-attachments/files/16402275/crash-2024-07-28_13.08.44-client.txt)

**Comment by Rajhab** [comment]
> Tested on neoForge beta 21.0.140 without any other mod present. Mod crashes specifically when opening inventory.
> 
> [crash-2024-07-28_13.08.44-client.txt](https://github.com/user-attachments/files/16402275/crash-2024-07-28_13.08.44-client.txt)
> 

Hey. Gonna look at it.

**Comment by Rajhab** [comment]
> Tested on neoForge beta 21.0.140 without any other mod present. Mod crashes specifically when opening inventory.
> 
> [crash-2024-07-28_13.08.44-client.txt](https://github.com/user-attachments/files/16402275/crash-2024-07-28_13.08.44-client.txt)
> 

@Ecthelion75 
Hello again. The error is because neoForge removed some functions since 21.0.76, which are used in the mod. 

There are actually two options for this fix:

1. You could use any other version from neFoege which iw under 21.0.76 (example: 21.0.75)

2. You can wait until today evening (german time zone) because I already wanted to release the new version with the fix and a new Shield. There you can use it with any version you want.


Hopefully this helps!

Greetings
@Rajhab

**Comment by Ecthelion75** [comment]
I'll wait for your fixed version. Thank you so much for the quick reply, looking forward to trying it out.

**Comment by Rajhab** [comment]
> I'll wait for your fixed version. Thank you so much for the quick reply, looking forward to trying it out.

Okay nice to know. Gonna ping younwhen update is released!

**Comment by Rajhab** [comment]
> I'll wait for your fixed version. Thank you so much for the quick reply, looking forward to trying it out.

Hey @Ecthelion75 

I got it fixed. 
You can launch it and use it like you want. A Redstone shield got added with some custom particles that hopefully work for server and client side. Of course your fix is also included. I can't upload it on curseforge for now because i still need to update all my other versions.

That is why I am going to upload it for you so you can get it to fix your problem. The official release should be tomorrow evening when I am finished with all version updates!

Hopefully it works and you have fun!

Greetings
@Rajhab 

[morevanillashields-1.0.1-1.21.jar](https://cdn.discordapp.com/attachments/1187337588210679860/1267198178453884998/morevanillashields-1.0.1-1.21.jar?ex=66a7e9c5&is=66a69845&hm=cc838fe0158c295d9fbb1e06f42dd40f72df5fc7ab7e79cfa019313808275518&)
