### ISSUE TITLE
Can't enchant in survival

### ISSUE THREAD

**Issue by Guesswho9000** [Rajhab/More-Vanilla-Shields-Forge#4]
Hi, I thought it was just a "full mod" issue, because I was not able to enchant the new shields, but when I tried it in creative, it worked. It isn't a level issue, it just shows the red X on the envil(in survival), but when I tried it in creative, it worked just as intended. Normal vanilla shield works, but the modded ones don't. I have no idea what causes it, I tried it without all other mods, but it didn't help:/
Version 1.21.1
Thx for help

**Comment by Rajhab** [comment]
> Hi, I thought it was just a "full mod" issue, because I was not able to enchant the new shields, but when I tried it in creative, it worked. It isn't a level issue, it just shows the red X on the envil(in survival), but when I tried it in creative, it worked just as intended. Normal vanilla shield works, but the modded ones don't. I have no idea what causes it, I tried it without all other mods, but it didn't help:/
> Version 1.21.1
> Thx for help

Hello. Thanks for the report. I know that the Issue is there. Trying to get it fixed for the next days. If you could wait some time I will upload a new Version with the fix. unfortunately i don't have so much time. Please be patient.

Sincerely
Rajhab

**Comment by Guesswho9000** [comment]
Hi, no problem:), I saw a similar comment on the mod page but no "issue report", so I thought the issue is on my side. The mod is briliant regardless. 
Can't wait for the fix, and thx for the quick reply:)

GW9

**Comment by Rajhab** [comment]
Hey @Guesswho9000 . I found the fix. I just need to apply the fix to every forge and neoforge version. Are you okay for waiting a few hours for the official release on curseforge or do you want the file here to be uploaded?

Thanks again!

**Comment by Guesswho9000** [comment]
Hi, wow...thank you very much for the quick fix:) And no problem, I can wait for the official release, you already spent a lot of your time working because of me, so I don't want any more work for you only for my convenience:)
Best regards
GW9

**Comment by Rajhab** [comment]
> Hi, wow...thank you very much for the quick fix:) And no problem, I can wait for the official release, you already spent a lot of your time working because of me, so I don't want any more work for you only for my convenience:) Best regards GW9

Hello again. You don't need to think like that :). I love modding and it is my task to make a successful mod and a happy community. People like you are the reason why I keep modding and why I love humans :). 

Thanks again for your bug report and I hope the update will fix your Issue.

Unfortunately the files are not getting uploaded to curseforge, for a reason i do not know. Tommorow afternoon the files will get uploaded again (hopefully). 

But you don't need to wait. I am uploading the file for you here. It is "unofficial" because the file is not released on curseforge yet.
You don't need to download this file if you feel unsecure. But if you want it is here till tommorow afternoon :).

[morevanillashields-1.0.2-1.21](https://cdn.discordapp.com/attachments/1187337588210679860/1290058433420070984/morevanillashields-1.0.2-1.21.jar?ex=66fb140a&is=66f9c28a&hm=8aae2be515ba4351364a08897b790bfeb5252139f444f769f465dc693f2a0a15&)


Greetings
Rajhab

**Comment by Rajhab** [comment]
Hey. All updates are now uploaded to curseforge.
Have a nice day and fun!

Greetings
Rajhab
